'use strict';
const unavailable = explanation => ({state:'unavailable',reason:'not_in_snapshot',explanation,evidenceSourceIds:[]});
function getDemoSnapshot() {
  const studentId='demo', sourceId='prototype-reference';
  const courses=[
    ['science','Environmental Science 9','Atmosphere, climate, and interpreting lab evidence.'],
    ['skills','Study Skills 9','Planning ahead and communicating what helps you learn.'],
    ['film','Beginning Film','Tell a story with action, framing, and visual sequence.'],
    ['english','English 9','Build a claim, gather evidence, and explain your thinking.'],
    ['math','Geometry','Show the steps behind a solution and review your reasoning.'],
    ['french','French 1','Numbers, pronunciation, and everyday conversation.'],
    ['history','History 9','Use artifacts and context to support historical claims.']
  ].map(([id,title,description])=>({id,studentId,title,description}));
  const resources=[];
  function preview(id,title,body,relationship='Prepared planning material for this design preview.') {
    resources.push({id,studentId,title,body,relationship,availability:{state:'available'},action:{kind:'preview',label:'Read prepared preview',url:null},sourceId});return id;
  }
  const labResources=[
    preview('lab-procedure','Greenhouse Gases Lab Procedure','Before writing: find your lab notes, identify the two conditions you compared, and put measurements in a table. Record units and the observation interval. Then describe the pattern before trying to explain it.\n\nPlanning prompt: What stayed the same? What changed? What evidence would make your conclusion stronger?','Resource title from the original prototype; this planning preview is newly authored, not the original lab handout.'),
    preview('lab-day3','Day 3: Greenhouse Gas Lab','Observation → evidence → explanation. Choose one observation from your own notes. Identify the measurements that support it. Explain how that evidence relates to the question the experiment asked.\n\nBefore finishing, flag one limitation or source of uncertainty.'),
    preview('lab-day2','Day 2: Atmosphere & Greenhouse Effect','Review prompts: How does energy enter and leave the Earth system? What role do greenhouse gases play? How is a classroom model different from the atmosphere?\n\nWrite a short explanation in your own words, then compare it with your course notes.'),
    preview('lab-prelab','U1 F — Greenhouse Gas Prelab','Pull forward your prediction and variables. Compare your prediction with the pattern you observed. If they differ, describe the difference without changing your original prediction.\n\nBring one question about the method or results to class.')
  ];
  const letterResources=[preview('letter-template','Teacher Letter template','Hi [teacher],\n\nI wanted to share a little about how I learn. One strength I bring to class is [strength]. Something I am working on is [challenge]. It helps when [specific support or strategy].\n\nMy goal for this class is [goal]. If I get stuck, I plan to [next step].\n\nThank you,\n[Your name]','Prepared editable starting point inspired by the prototype’s letter-template link; not an official course template.')];
  const make=(id,courseId,title,dueAt,state,description,nextAction,resourceIds,extra={})=>({id,studentId,courseId,title,dueAt,dueAvailability:dueAt?{state:'available'}:unavailable('No deadline is set for this preview item. Add a date once the instructions establish one.'),submission:{state,sourceId},feedback:[],resourceIds,sourceId,description,nextAction,...extra});
  const assignments=[
    make('email','science','U0: About me email & Sign Syllabus','2026-09-08T15:00:00-07:00','missing','A two-part introduction: an About Me message and a syllabus check. This preview explores how Hallway can help untangle a missing flag without assuming the work was never done.','Check Sent mail for the introduction, then confirm the syllabus step. If something is unclear, use a follow-up draft.',[preview('email-guide','About Me message starter','Introduce yourself with one interest, one learning goal, and one thing that helps you participate. Keep it short and specific.\n\nBefore sending in your usual email app: confirm the recipient, subject, and requested syllabus step.')],{checklist:['Look for the About Me email in Sent','Check the syllabus step','Write down anything that needs follow-up'],feedback:[{author:'Placeholder message',text:'This is where a teacher clarification could appear: “Please check the email portion of the introduction.”',postedAt:null,sourceId}]}),
    make('lab','science','Greenhouse Gases Post Lab Questions','2026-09-18T15:00:00-07:00','not_submitted','Turn observations from the greenhouse-gas activity into an evidence-based explanation. The original prototype linked the lab procedure, two lesson pages, and the prelab; all four now have prepared planning previews.','Open your observations and choose the clearest pattern. Use a measurement to support it, then explain what it means.',labResources,{checklist:['Gather notes and measurements','State one pattern with evidence','Explain a limitation','Review the original questions before submitting']}),
    make('letter','skills','Teacher Letter','2026-09-18T15:00:00-07:00','not_submitted','Introduce your learning strengths, goals, and useful support strategies. The original design described a letter to eight teachers and an advisor; the checklist below makes that multi-recipient task visible.','Start with the prepared template, personalize it, then use the recipient checklist to plan each send.',letterResources,{checklist:[...Array.from({length:8},(_,i)=>'Teacher '+(i+1)),'Advisor']}),
    make('film','film','Script for Silent Film','2026-09-21T21:00:00-07:00','not_submitted','Plan a short story that makes sense without spoken dialogue. This prepared brief gives the original film tile a useful place to begin.','Write the beginning, turning point, and ending as visible actions. Then list the shots needed to make each beat clear.',[preview('film-beats','Silent film beat sheet','Beginning: Who is here, and what do they want?\nObstacle: What gets in the way?\nTurning point: What choice changes the situation?\nEnding: What image shows the result?\n\nFor every beat, list an action the camera can see. Mark any prop, location, or shot you need. Replace explanation with visible behavior.')],{checklist:['Write three visual story beats','List shots and props','Check the story without dialogue']}),
    make('english','english','Graphic Organizer','2026-09-22T15:00:00-07:00','not_submitted','Organize an idea before drafting. This prepared structure connects a claim with evidence and the explanation that makes the evidence matter.','Choose one claim. Add two pieces of evidence, then explain how each supports the claim.',[preview('organizer','Claim → evidence → explanation','Working claim: [What do you want the reader to understand?]\n\nEvidence 1: [Passage, detail, or observation]\nWhy it matters: [Explain the connection]\n\nEvidence 2: [A different supporting detail]\nWhy it matters: [Explain the connection]\n\nPossible complication: [What might challenge or qualify the claim?]\nNext paragraph: [What should follow?]')]),
    make('undated','science','Unit 1 Extension Checklist',null,'unknown','An extension slot for questions and connections that do not yet have a deadline. It stays on the board so an undated task does not disappear.','Choose one open question from the unit and note what you would need to investigate it.',[preview('extension','Extension planning prompts','One question I still have: […]\nA connection to something outside class: […]\nEvidence I would need: […]\nA useful first step: […]\n\nConfirm whether this is optional and when it should be discussed before adding it to your plan.')]),
    make('math','math','HW 1.3','2026-09-16T15:00:00-07:00','submitted','A completed-work tile stays useful as a place for reflection and follow-up. The problem set itself is not included.','Pick one problem to explain aloud. Note the step that required the most thought.',[preview('geometry-review','Geometry review prompts','Sketch the figure. Label what is given and what needs to be found. Name the relationship or rule you used.\n\nIf your answer seems surprising, check the units, diagram, and assumptions. Save one question for the next class.')]),
    make('french','french','Quiz: Les chiffres','2026-09-16T15:00:00-07:00','submitted','A numbers assessment from the original board. This preview includes a practice idea without displaying results or grades.','Practice reading a short set of numbers aloud, then check the pronunciation against your class materials.',[preview('french-practice','Numbers practice plan','Choose five numbers from your notes. Say each aloud, write it in words, and use it in a short phrase such as an age, date, or quantity.\n\nMix the order for a second pass. Mark any number you want to hear again in class.')],{kind:'assessment'}),
    make('history','history','U1 L2: Archaeology','2026-09-17T15:00:00-07:00','submitted','The original changes strip included an archaeology feedback card. This version uses an explicit placeholder message to demonstrate where a useful follow-up would live.','Separate what an artifact shows directly from what you infer about the people who used it.',[preview('artifact','Artifact evidence notes','What can you observe directly? [material, shape, markings, location]\nWhat might it suggest? [purpose or context]\nWhat else would you need to know? [comparison, date, surrounding finds]\n\nKeep observations and interpretations in separate columns.')],{feedback:[{author:'Placeholder message',text:'A future feedback card could say: “Add the observation that supports your interpretation, and note one alternative explanation.”',postedAt:null,sourceId}]})
  ];
  return {contractVersion:'0.1',exampleOnly:true,snapshot:{id:'hallway-design-preview',mode:'frozen_demo',student:{id:studentId,displayName:'Design preview'},capturedAt:null,demoNow:'2026-09-18T13:43:00-07:00',timeZone:'America/Los_Angeles',coverage:{state:'not_captured',windowStart:'2026-09-08T00:00:00-07:00',windowEnd:'2026-10-18T23:59:59-07:00',includedCourseIds:courses.map(c=>c.id),explanation:'Coursework from the original Hallway design, expanded with prepared planning content. Dates and statuses are preview scenarios, not current school records.'}},courses,assignments,resources,sources:[{id:sourceId,studentId,title:'Original Hallway prototype + prepared previews',url:null,checkedAt:null,retrieval:{state:'not_captured'},provenance:'Assignment and resource titles reference Hallway Prototype (patched)_2.html. Descriptions, checklists, messages, and resource bodies are authored design content, not verified coursework or student records.'}],changes:[{id:'letter-change',studentId,assignmentId:'letter',type:'due_date',label:'Due date moved',summary:'Now today, 3:00 PM',previousValue:null,previousAvailability:unavailable('The earlier date was not included in the original design.'),newValue:'2026-09-18T15:00:00-07:00',sourceId},{id:'organizer-added',studentId,assignmentId:'english',type:'new_assignment',label:'New assignment',summary:'English 9 · due Tuesday',sourceId},{id:'history-feedback',studentId,assignmentId:'history',type:'feedback',label:'Feedback preview',summary:'A next step from a comment',sourceId}]};
}
module.exports={getDemoSnapshot};
