'use strict';
const unavailable = (reason, explanation) => ({state:'unavailable',reason,explanation,evidenceSourceIds:[]});
function getFixture(studentId) {
  if (!['max','adrian'].includes(studentId)) throw new Error('Unknown fixture identity');
  const sourceId='fictional-source';
  const courses=[{id:'science',studentId,title:'Example Science',teacher:'Fictional teacher'},{id:'writing',studentId,title:'Example Writing',teacher:'Fictional teacher'},{id:'math',studentId,title:'Example Mathematics',teacher:'Fictional teacher'}];
  const make=(id,courseId,title,dueAt,state,extra={})=>({id,studentId,courseId,title,dueAt,dueAvailability:dueAt?{state:'available'}:unavailable('not_in_snapshot','No due date is included in this fictional example.'),submission:{state,sourceId},grade:{value:null,pointsPossible:null,availability:unavailable('unknown','A grade is not provided in this example; this does not mean zero.')},feedback:[],resourceIds:[],sourceId,...extra});
  return {contractVersion:'0.1',exampleOnly:true,snapshot:{id:'fictional-'+studentId,mode:'frozen_demo',student:{id:studentId,displayName:(studentId==='max'?'Max':'Adrian')+' — fictional demo'},capturedAt:null,demoNow:'2026-09-18T13:43:00-07:00',timeZone:'America/Los_Angeles',coverage:{state:'not_captured',windowStart:'2026-09-08T00:00:00-07:00',windowEnd:'2026-10-18T23:59:59-07:00',includedCourseIds:courses.map(c=>c.id),explanation:'Fictional sample only. No personal school snapshot has been captured; this is not a complete work list.'}},courses,assignments:[
  make('welcome','science','Example welcome note','2026-09-08T15:00:00-07:00','missing',{grade:{value:5,pointsPossible:5,availability:{state:'available'}},feedback:[{author:'Fictional teacher',text:'Example comment: please check the welcome note.',postedAt:null,sourceId}],nextAction:'Check the example instructions and your sent email. A missing flag does not prove that you never sent it.'}),
  make('reflection','science','Example lab reflection','2026-09-18T15:00:00-07:00','not_submitted',{resourceIds:['lab-preview','lab-source'],descriptionAvailability:unavailable('not_in_snapshot','Full assignment instructions are not included in this fictional sample.'),nextAction:'Review the bundled example and check the full assignment instructions before starting.'}),
  make('letter','writing','Example learning letter','2026-09-18T15:00:00-07:00','unknown',{nextAction:'Check the confirmed deadline and actual recipients. The previous deadline is unavailable.'}),
  make('outline','writing','Example argument outline','2026-09-22T15:00:00-07:00','not_submitted'),
  make('practice','math','Example practice set','2026-09-16T15:00:00-07:00','submitted'),
  make('quiz','math','Example vocabulary assessment','2026-09-16T15:00:00-07:00','submitted',{kind:'assessment',grade:{value:8,pointsPossible:10,availability:{state:'available'}}}),
  make('undated','science','Example optional checklist',null,'unknown')],resources:[
  {id:'lab-preview',studentId,title:'Bundled lab example',availability:{state:'available'},body:'Prepared fictional example: list one observation, describe the evidence, and write one question. This is a UI demonstration, not verified course material or an AI answer.',relationship:'Linked to the fictional reflection for demonstration only.',action:{kind:'preview',label:'Read prepared example',url:null},sourceId},
  {id:'lab-source',studentId,title:'Original lab instructions',availability:unavailable('not_in_snapshot','The original material is not included in this demo. No verified source link was captured.'),action:{kind:'none',label:'No source link captured',url:null},sourceId}],sources:[{id:sourceId,studentId,title:'Authored fictional UI fixture',url:null,checkedAt:null,retrieval:{state:'not_captured'},provenance:'Created solely to exercise Hallway interactions; not a school record.'}],changes:[{id:'letter-change',studentId,assignmentId:'letter',type:'due_date',previousValue:null,previousAvailability:unavailable('not_recorded','Previous value unavailable. This example does not include an earlier deadline.'),newValue:'2026-09-18T15:00:00-07:00',sourceId}],reasonCodes:['not_in_snapshot','access_denied','empty_at_source','not_recorded','not_yet_posted','fetch_failed','unsupported','unknown','not_built']};
}
module.exports={getFixture};
